### ISSUE TITLE
archiveWithCpack depends on order of environment variable values

### ISSUE THREAD

**Issue by ahuber21** [PanDAWMS/panda-client#16]
In this line

https://github.com/PanDAWMS/panda-client/blob/master/pandatools/AthenaUtils.py#L1062

```python
buildDir = os.path.dirname(buildDir.split(':')[0])
```

exactly value `[0]` is taken as the buildDir.  `CMAKE_PREFIX_PATH` is a variable that some users modify and this is very risky. In particular as it leads to very inscrutable behaviour when used within `prun`. Isn't there a better way of determining the user's build directory?

I only found this issue after many hours of debugging. I started from grid jobs that failed with the error

```
TBufferFile::ReadObject   ERROR   trying to read an emulated class (AnalysisBase_VHbb) to store in a compiled pointer (EL::Algorithm)
```

**Comment by tmaeno** [comment]
This was recommended by offline experts like Attila. I thought that CMAKE_PREFIX_PATH was automatically set by cmake. If you need to manually change it I suppose that first you should talk to offline experts.

**Comment by ahoenle** [comment]
Okay in my case it was sometimes not set correctly and maybe I executed some commands in the wrong order. Still, locally everything works and submitted jobs break. So it's really tricky. I already contacted the mailings lists, so Attila and co are informed.
