### ISSUE TITLE
Use setuptools over deprecated distutils

### ISSUE THREAD

**Issue by matthewfeickert** [PanDAWMS/panda-client#21]
As noted in PR #20:

In the `sdist` creation phase of the build there is currently the warning:

```console
$ python setup.py sdist
/home/runner/work/panda-client/panda-client/setup.py:6: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils
...
```

The use of `distutils` in `setup.py`

https://github.com/PanDAWMS/panda-client/blob/3c2aee0d6f8cfeed64c46556b069f9564dd27478/setup.py#L1-L16

https://github.com/PanDAWMS/panda-client/blob/3c2aee0d6f8cfeed64c46556b069f9564dd27478/setup.py#L26-L33

https://github.com/PanDAWMS/panda-client/blob/3c2aee0d6f8cfeed64c46556b069f9564dd27478/setup.py#L53

should be replaced with `setuptools` commands.

**Comment by tmaeno** [comment]
https://github.com/PanDAWMS/panda-client/commit/f84712b9b3a0d1c94db80df083f69330e5a08264
