### ISSUE TITLE
Document Dependencies for standalone install

### ISSUE THREAD

**Issue by lukasheinrich** [PanDAWMS/panda-client#3]
Hello,

ATLAS is looking into installing standalone Docker Images for its software releases and for that we'd like to install the panda clients in them. Can yo document the software dependencies (and dependencies on things like EGI trust anchors etc? A while back we had a prototype, but i'm not sure if the EGI things are still applicable

https://github.com/lukasheinrich/asg-docker/blob/master/preasg-base/Dockerfile

Thanks,
Lukas

**Comment by tmaeno** [comment]
panda-client itself doesn't have any  dependencies on external software. It indirectly requires voms-proxy-* for a grid proxy and CERN CA cert to access panda which are included in the standard ATLAS grid middleware stack. For the middleware stack, better to check with Asoka.
