### ISSUE TITLE
ramCount

### ISSUE THREAD

**Issue by ericballabene** [PanDAWMS/panda-client#37]
Hello,

I got 
retry(41882731, ramCount=5000)
Error: Unknown option name "ramCount"

but also
retry(41882731, memory=5000)
INFO : reactivation accepted. jediTaskID=41882731 (currently in finished state) will be re-executed with old and/or new input

is it expected that ramCount doesn't work anymore?

**Comment by tmaeno** [comment]
Yes, please use memory instead of ramCount https://its.cern.ch/jira/browse/ATLASPANDA-1172
