### ISSUE TITLE
secondaryDS containing colon breaks

### ISSUE THREAD

**Issue by lukasheinrich** [PanDAWMS/panda-client#6]
With rucio scoping patterns `scope:datasetname` using such a dataset as a secondary dataset seems to break since prun splits on ':'

I craeted this test

```
prun --exec "echo %IN; echo %HELLO; find ." --inDS user.lheinric:multiDStest1 --secondaryDS HELLO:1:user.lheinric:multiDStest1.secondary --outDS user.lheinric:multiDStest.out.v2 --forceStaged --site ANALY_MANC_GPU_TEST --noBuild
```

https://bigpanda.cern.ch/task/16164344/

**Comment by tmaeno** [comment]
\# can be used as a separator for --secondaryDS in 0.6.10.

**Comment by afortiorama** [comment]
Hi Tadashi, 

we have another problem with secondaryDS. If we split the primary input dataset into using nFilesPerJob the secondary datasets get used only in the first job. Is that how is it supposed to work? We need to have 2 files as input for all the jobs. How can we do that?

thanks

cheers
alessandra

**Comment by afortiorama** [comment]
I forgot to put an example of task that failed in this way https://bigpanda.cern.ch/task/16204845/

**Comment by tmaeno** [comment]
I suppose you need --reusableSecondary=IN2,IN3

**Comment by lukasheinrich** [comment]
@tmaeno can you explain what the difference would be?

**Comment by tmaeno** [comment]
```
--reusableSecondary=REUSABLESECONDARY
                        A comma-separated list of secondary streams which
                        reuse files when all files are used
```
Without this (default), files are used only once.

**Comment by afortiorama** [comment]
I've submitted a task with the extra parameter. 

https://bigpanda.cern.ch/task/16219599/
